# Generated by Django 3.0.2 on 2020-09-29 03:07

import django.core.validators
from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=200, validators=[feedback.models.validate_first])),
                ('field2', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(534820), django.core.validators.MaxValueValidator(534830)])),
                ('field3', models.CharField(max_length=200, validators=[feedback.models.validate_third])),
                ('field4', models.CharField(max_length=200, validators=[feedback.models.validate_fourth])),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
