# Generated by Django 3.0.2 on 2020-09-29 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='field2',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(531240), django.core.validators.MaxValueValidator(531270)]),
        ),
    ]
