# Generated by Django 3.0.2 on 2020-09-29 02:52

import django.core.validators
from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200925_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='field1',
            field=models.CharField(max_length=200, validators=[feedback.models.validate_first]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='field2',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(534820), django.core.validators.MaxValueValidator(534830)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='field3',
            field=models.CharField(max_length=200, validators=[feedback.models.validate_third]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='field4',
            field=models.CharField(max_length=200, validators=[feedback.models.validate_fourth]),
        ),
    ]
